-- for participants
INSERT INTO `pwm_data` . `participants` (`id`, `first_name`, `last_name`, `date_of_birth`, `gender`) VALUES ('0', 'istvan', 'gates', '1111995', 'male');

-- for question_responses
INSERT INTO `pwm_data`.`question_responses` (`id`, `name`) VALUES ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10');

-- for question_links
INSERT INTO `pwm_data` . `question_links` (`from_question`, `to_question`, `condition`) VALUES ('0', '1', '0'), ('1', '10', '5'), ('1', '10', '6'), ('1', '10', '7'), ('1', '10', '8'), ('1', '10', '9'), ('1', '10', '10'), ('10', '2', '5'), ('10', '2', '6'), ('10', '2', '7'), ('10', '2', '8'), ('10', '2', '9'), ('10', '2', '10'), ('1', '11', '4'), ('1', '11', '3'), ('1', '11', '2'), ('1', '11', '1'), ('10', '12', '4'), ('10', '12', '3'), ('10', '12', '2'), ('10', '12', '1'), ('0', '13', '1'), ('13', '3', '4'), ('13', '3', '5'), ('13', '3', '6'), ('13', '3', '7'), ('13', '3', '8'), ('13', '3', '9'), ('13', '3', '10'), ('3', '14', '5'), ('3', '14', '6'), ('3', '14', '7'), ('3', '14', '8'), ('3', '14', '9'), ('3', '14', '10'), ('13', '14', '3'), ('13', '14', '2'), ('13', '14', '1'), ('3', '1', '4'), ('3', '1', '3'), ('3', '1', '2'), ('3', '1', '1');

-- for question_types
INSERT INTO `pwm_data` . `question_types` (`id`, `name`) VALUES ('0', 'bigq'), ('1', 'checkbox'), ('2', 'mc'), ('3', 'agreedisagree'), ('4', 'agreedisagree_vector'), ('5', 'mc_vector'), ('6', 'checkbox_vector'), ('7', 'bigq_vector');
-- for base case
INSERT INTO `question_types`(`id`, `name`) VALUES ('8','Base Question');


-- for squential_questions

INSERT INTO `pwm_data`.`sequential_questions` (`id`, `type`, `dimension`, `text`) VALUES ('0', '0', NULL, 'I regularly participate in exercise'), ('1', '3', NULL, 'Skills training'), 
('2', '3', NULL, 'Observed behavior'), ('3', '3', NULL, 'Perceived Social Support'), ('4', '3', NULL, 'Environmental context'), 
('5', '3', NULL, 'Internal Cues'), ('6', '3', NULL, 'External Cues'), ('7', '3', NULL, 'Adherence'), 
('8', '3', NULL, 'Autonomy'), ('9', '3', NULL, 'Self-Satisfaction'), ('10', '2', NULL, 'What is the average duration of an exercise session?'), 
('11', '2', NULL, 'How often do you exercise?'), ('12', '2', NULL, 'How long have you exercised at that level? '), ('13', '1', NULL, 'These are the reasons I do not exercise: '), 
('14', '1', NULL, 'When I hear the word exercise, I feel: '), ('15', '7', NULL, 'Yes'), ('16', '5', NULL, '1-15 minutes'), 
('17', '5', NULL, '15-30 minutes'), ('18', '5', NULL, '30-45 minutes'), ('19', '5', NULL, '45+ minutes'), 
('20', '5', NULL, '1-2 times a week'), ('21', '5', NULL, '2-3 times a week'), ('22', '5', NULL, '3-4 times a week'), 
('23', '5', NULL, '4+ times a week'), ('24', '5', NULL, '1 week-3 months'), ('25', '5', NULL, '3-6 months'), 
('26', '5', NULL, '6-9 months'), ('27', '5', NULL, '9-12 months'), ('28', '5', NULL, '12+ months'), 
('29', '6', NULL, 'I do not have enough time'), ('30', '6', NULL, 'Exercising costs too much money and I cannot afford it'), ('31', '6', NULL, 'I do not know how to exercise correctly'), 
('32', '6', NULL, 'I am or have been previously injured and cannot exercise'), ('33', '6', NULL, 'Work gets in the way of exercising'), ('34', '6', NULL, 'I have no access to an exercise facility'), 
('35', '6', NULL, 'The location I lives at prevents me from exercising'), ('36', '6', NULL, 'People say that I will fail if I try exercising'), ('37', '6', NULL, 'I am not confident that I can exercise'), 
('38', '6', NULL, 'Happy'), ('39', '6', NULL, 'Sad'), ('40', '6', NULL, 'Motivated'), 
('41', '6', NULL, 'Excited'), ('42', '6', NULL, 'Depressed'), ('43', '6', NULL, 'Angry'), 
('44', '6', NULL, 'Ashamed'), ('45', '6', NULL, 'Afraid'), ('46', '6', NULL, 'Enthusiastic'), 
('47', '4', NULL, 'I am confident that I can perform exercise with the correct and recommended form '), ('48', '4', NULL, 'I have been trained by an exercise specialist and know how to participate in physical activity safely and efficiently'), ('49', '4', NULL, 'Prior to participation, I learn the correct and recommended way to perform an exercise'), 
('50', '4', NULL, 'Because of previous training, I know how to exercise efficiently by myself'), ('51', '4', NULL, 'I am aware of the risk factors involved with exercise, I learned the correct way to perform specific activity to avoid those risks'), ('52', '4', NULL, 'Through self-regulation, I participate in only safe forms of physical activity'), 
('53', '4', NULL, 'I will be able to perform specific exercises because I have learned the correct way to perform them myself'), ('54', '4', NULL, ' I am aware of many different forms of physical activity that is considered to be exercise and can participate in the activity safety'), ('55', '4', NULL, 'My self-management skills have allowed me to engage in exercise using the recommended forms to ensure safety'), 
('56', '4', NULL, ' I am confident in the knowledge I have for exercise, this confidence allows me to perform physical activity correctly'), ('57', '4', NULL, 'I notice that people I interact with throughout my day discuss their exercise habits'), ('58', '4', NULL, 'My friends, family, or co-workers participate in regular physical activity'), 
('59', '4', NULL, 'I often see people exercising when I am going about my day to day activities'), ('60', '4', NULL, 'Someone that I am close with participates in regular exercise and has informed be about their results'), ('61', '4', NULL, 'I see people participating in exercise on social media'), 
('62', '4', NULL, 'I often see people participating in physical activity i.e. sports, game shows, commercials, while I am watching TV or using social media'), ('63', '4', NULL, 'I see people using an exercise facility on my daily commute'), ('64', '4', NULL, 'Some one that I look up to participates in regular physical activity'), 
('65', '4', NULL, 'I often hear about people’s exercise success stories'), ('66', '4', NULL, ' I see exercise as a trending topic discussed by peers '), ('67', '4', NULL, 'I feel that I can depend on my friends, family, co-workers to encourage me to participate in regular exercise'), 
('68', '4', NULL, 'My friends, family, and co-workers will give me the support I need to feel as though I can perform exercise'), ('69', '4', NULL, 'My friends, family, and co-workers will reinforce my positive exercise habits and encourage me to avoid a sedentary lifestyle'), ('70', '4', NULL, 'I usually participate in exercise'), 
('71', '4', NULL, 'In times of doubt I can count on my friends, family, and co-workers to remind me that I can perform exercise '), ('72', '4', NULL, 'I have the support channels I need that will encourage me to exercise regularly even when I doubt myself'), ('73', '4', NULL, 'When challenged with barriers, my friends, family, and co-workers will help encourage me to overcome those barriers and exercise'), 
('74', '4', NULL, 'I know I am not alone, I have friends, family and co-workers that will help me perform physical activity'), ('75', '4', NULL, 'I have a people in my life that I can turn to in times of doubt that will encourage me to perform physical activity and stay committed '), ('76', '4', NULL, 'I know that my friends, family, and coworkers are proud when I exercise and support my goals'), 
('77', '4', NULL, 'When I am discouraged, my friends, family and co-workers make me feel like I can accomplish exercise goals'), ('78', '4', NULL, 'I have access to multiple areas to perform safe physical activity in my nearby location'), ('79', '4', NULL, 'There are many ways I can exercise in my community safe and efficiently '), 
('80', '4', NULL, 'My community offers many outlets to perform physical activity safely'), ('81', '4', NULL, 'The location where I live allows me to have multiple options of different forms of exercise'), ('82', '4', NULL, 'The community I live in provides multiple attractions where I can perform physical activity'), 
('83', '4', NULL, 'There are multiple ways to perform physical activity in the community I live in'), ('84', '4', NULL, 'The location where I live gives me realistic ways to participate in exercise'), ('85', '4', NULL, 'There are many different attractions to perform exercise near where I live such as parks, well maintained community, and affordable exercise facilities'), 
('86', '4', NULL, 'My community makes physical activity realistic because it is well maintained and had several exercise facilities nearby '), ('87', '4', NULL, 'The location where I live has many different channels to perform different kinds of physical activity'), ('88', '4', NULL, 'I feel that I need to exercise for myself'), 
('89', '4', NULL, 'If I do not exercise, I feel guilty'), ('90', '4', NULL, 'I feel guilty when I do not perform any form of physical activity during the day/week'), ('91', '4', NULL, 'I feel happy after I exercise, therefore, I participate in exercise'), 
('92', '4', NULL, 'If I do not perform physical activity, I am upset with myself'), ('93', '4', NULL, 'I want to see changes in myself, therefore I participate in physical activity'), ('94', '4', NULL, 'If I do not exercise, I am disappointed in myself'), 
('95', '4', NULL, 'Physical activity makes me feel good about myself, there for I exercise'), ('96', '4', NULL, 'I am afraid of the consequences of being sedentary, therefore I participate I regular exercise'), ('97', '4', NULL, 'I feel ashamed if I do not perform regular physical activity'), 
('98', '4', NULL, 'My healthcare provider will be upset at me if I do not participate in exercise'), ('99', '4', NULL, 'I will let down my friends, family, and co-workers if I do not exercise, therefore I engage in physical activity'), ('100', '4', NULL, 'I exercise to make my friends, family, and co-workers proud of my behavior'), 
('101', '4', NULL, 'I exercise to be more like my surrounding peers'), ('102', '4', NULL, 'I know my doctor will get mad if I do not exercise, there for I perform physical activity'), ('103', '4', NULL, 'To prevent my friends family and coworkers from being disappointed in me, I exercise'), 
('104', '4', NULL, 'I exercise regularly to because my friends, family, and co-workers do'), ('105', '4', NULL, 'Health risks scare me, therefore I participate in physical activity'), ('106', '4', NULL, 'I know I will not be able to participate in things I enjoy unless I perform exercise and stay conditioned'), 
('107', '4', NULL, 'I commit to my exercise goals and plan my schedule around them to accomplish these goals'), ('108', '4', NULL, 'Once I start an exercise program, I finish it'), ('109', '4', NULL, 'I feel committed to regular physical activity and prioritize working it in my schedule'), 
('110', '4', NULL, 'I create ways to stay focused and accomplish the exercise goals I set'), ('111', '4', NULL, 'If I do not exercise one day, I adjust my schedule to complete that specific exercise'), ('112', '4', NULL, 'I overcome challenges that get in my way when I try to exercise'), 
('113', '4', NULL, 'Exercise goals are important to me because once I set a goal, I commit to it until that goal is complete'), ('114', '4', NULL, ' Once I set a goal, I prioritize it and adjust my schedule to contribute to that goal'), ('115', '4', NULL, 'I never back out of a commitment '), 
('116', '4', NULL, ' If I say I am going to exercise that day, I will exercise '), ('117', '4', NULL, 'I have the freedom to decide if I should exercise or not'), ('118', '4', NULL, 'I am in control of my exercise habits'), 
('119', '4', NULL, 'I believe exercise is important and value that opinion over the opinion of someone else'), ('120', '4', NULL, 'I am the only one who can decide if I exercise or not'), ('121', '4', NULL, 'I have the power to determine whether I participate in physical activity or not'), 
('122', '4', NULL, 'It is my choice to exercise or not'), ('123', '4', NULL, 'No one else can control my decision to exercise or not'), ('124', '4', NULL, 'No one else’s actions or option about my exercise habits will prevent me from exercising '), 
('125', '4', NULL, 'I have the freedom to participate in physical activity if I choose to do so'), ('126', '4', NULL, 'I know I am free to exercise and participate in physical activity'), ('127', '4', NULL, 'I have a sense of satisfaction because of my current exercise behavior'), 
('128', '4', NULL, 'I am proud in my current exercise habits'), ('129', '4', NULL, 'When I look at my exercise habits, I am happy with the results'), ('130', '4', NULL, 'I have self-confidence because of my current exercise habits'), 
('131', '4', NULL, 'I have a high level of self-worth because I exercise'), ('132', '4', NULL, 'I am proud in myself because of my exercise habits '), ('133', '4', NULL, 'I do not feel guilt about exercise because I perform physical activity on a regular basis and it makes me feel good about myself'), 
('134', '4', NULL, 'My self-confidence level is high because I perform regular physical activity and am proud of my results '), ('135', '4', NULL, 'I exercise frequently and am satisfied with my lifestyle habits'), ('136', '4', NULL, 'The lifestyle habits make me feel proud because I exercise regularly '), ('137', '7', NULL, 'No'), ('138', '6', NULL, 'THIS IS A PLACEHOLDER, ONLY 9  FOR VECTOR 6, THIS IS the 10th');
INSERT INTO `pwm_data`.`sequential_questions` (`id`, `type`, `dimension`, `text`) VALUES ('139', '8', NULL, 'Motivational Interviewing, Social Cognitive Theory');

-- for question_vectors
INSERT INTO `pwm_data` . `question_vectors` (`vector_id`, `question_id`) VALUES ('0', '15'), ('0', '137'), ('10', '16'), ('10', '17'), ('10', '18'), ('10', '19'), ('11', '20'), ('11', '21'), ('11', '22'), 
('11', '23'), ('12', '24'), ('12', '25'), ('12', '26'), ('12', '27'), ('12', '28'), ('13', '29'), ('13', '30'), ('13', '31'), ('13', '32'), ('13', '33'), ('13', '34'), ('13', '35'), ('13', '36'), ('13', '37'),
('14', '38'), ('14', '39'), ('14', '40'), ('14', '41'), ('14', '42'), ('14', '43'), ('14', '44'), ('14', '45'), ('14', '46'), ('1', '47'), ('1', '48'), ('1', '49'), ('1', '50'), ('1', '51'), ('1', '52'), 
('1', '53'), ('1', '54'), ('1', '55'), ('1', '56'), ('2', '57'), ('2', '58'), ('2', '59'), ('2', '60'), ('2', '61'), ('2', '62'), ('2', '63'), ('2', '64'), ('2', '65'), ('2', '66'), ('3', '67'), ('3', '68'), 
('3', '69'), ('3', '70'), ('3', '71'), ('3', '72'), ('3', '73'), ('3', '74'), ('3', '75'), ('3', '76'), ('4', '77'), ('4', '78'), ('4', '79'), ('4', '80'), ('4', '81'), ('4', '82'), ('4', '83'), ('4', '84'),
('4', '85'), ('4', '86'), ('5', '87'), ('5', '88'), ('5', '89'), ('5', '90'), ('5', '91'), ('5', '92'), ('5', '93'), ('5', '94'), ('5', '95'), ('5', '96'), ('6', '97'), ('6', '98'), ('6', '99'), ('6', '100'), 
('6', '101'), ('6', '102'), ('6', '103'), ('6', '104'), ('6', '105'), ('6', '138'), ('7', '106'), ('7', '107'), ('7', '108'), ('7', '109'), ('7', '110'), ('7', '111'), ('7', '112'), ('7', '113'), ('7', '114'), 
('7', '115'), ('8', '116'), ('8', '117'), ('8', '118'), ('8', '119'), ('8', '120'), ('8', '121'), ('8', '122'), ('8', '123'), ('8', '124'), ('8', '125'), ('9', '126'), ('9', '127'), ('9', '128'), ('9', '129'),
('9', '130'), ('9', '131'), ('9', '132'), ('9', '133'), ('9', '134'), ('9', '135');
INSERT INTO `pwm_data`.`question_vectors` (`vector_id`, `question_id`) VALUES ('139', '0');